project:
  type: book
  output-dir: docs

book:
  title: "Modul Psikometri: Item Response Theory (IRT)"
  subtitle: "Panduan Praktis untuk Analis SDM dan Peneliti"
  author: "Aswin Januarsjaf"
  date: "2025"
  date-format: "MMMM YYYY"
  language: id

  sidebar:
    style: "docked"
    search: true

  chapters:
    - index.qmd
    - part: "Bagian I: Fondasi Teori"
      chapters:
        - bab01-pengantar.qmd
        - bab02-classical-test-theory.qmd
        - bab03-teori-irt.qmd
    - part: "Bagian II: Model-Model IRT"
      chapters:
        - bab04-model-1pl.qmd
        - bab05-model-2pl.qmd
        - bab06-model-3pl.qmd
        - bab07-rasch-model.qmd
    - part: "Bagian III: Implementasi di R"
      chapters:
        - bab08-setup-r.qmd
        - bab09-estimasi-parameter.qmd
        - bab10-item-fit.qmd
        - bab11-person-fit.qmd
    - part: "Bagian IV: Aplikasi Praktis"
      chapters:
        - bab13-wright-map.qmd
        - bab14-computer-adaptive.qmd
        - bab15-pelaporan.qmd


        
    - referensi.qmd

   

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: github
    toc: true
    toc-depth: 4
    toc-title: "Daftar Isi Bab"
    number-sections: true
    number-depth: 3
    code-fold: true
    code-tools: true
    code-copy: true
    fig-align: center
    fig-width: 7
    fig-height: 5
    callout-appearance: minimal
    smooth-scroll: true

  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - bottom=30mm
      - left=25mm
      - right=25mm

execute:
  echo: true
  warning: false
  message: false
  cache: true